language: ruby

rvm:
  - 1.9.3
  - 2.0.0

bundler_args: --without development production --quiet

before_script:
  - "bundle exec rake test_app"

script: "DISPLAY=:99.0 bundle exec rspec spec"

notifications:
  email:
    - weston+notifications@think602.com
