language: ruby

rvm:
  - 1.9.3
  - 2.0.0

before_script:
  - "bundle exec rake test_app"

script: "DISPLAY=:99.0 bundle exec rake spec"

notifications:
  hipchat:
    rooms:
      - 48043dcd347f6ba6de724cab65b1a0@notifications
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'

