require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WizardsController do

  # This should return the minimal set of attributes required to create a valid
  # Wizard. As you add validations to Wizard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WizardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all wizards as @wizards" do
      wizard = Wizard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wizards).should eq([wizard])
    end
  end

  describe "GET show" do
    it "assigns the requested wizard as @wizard" do
      wizard = Wizard.create! valid_attributes
      get :show, {:id => wizard.to_param}, valid_session
      assigns(:wizard).should eq(wizard)
    end
  end

  describe "GET new" do
    it "assigns a new wizard as @wizard" do
      get :new, {}, valid_session
      assigns(:wizard).should be_a_new(Wizard)
    end
  end

  describe "GET edit" do
    it "assigns the requested wizard as @wizard" do
      wizard = Wizard.create! valid_attributes
      get :edit, {:id => wizard.to_param}, valid_session
      assigns(:wizard).should eq(wizard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wizard" do
        expect {
          post :create, {:wizard => valid_attributes}, valid_session
        }.to change(Wizard, :count).by(1)
      end

      it "assigns a newly created wizard as @wizard" do
        post :create, {:wizard => valid_attributes}, valid_session
        assigns(:wizard).should be_a(Wizard)
        assigns(:wizard).should be_persisted
      end

      it "redirects to the created wizard" do
        post :create, {:wizard => valid_attributes}, valid_session
        response.should redirect_to(Wizard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wizard as @wizard" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wizard.any_instance.stub(:save).and_return(false)
        post :create, {:wizard => { "name" => "invalid value" }}, valid_session
        assigns(:wizard).should be_a_new(Wizard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wizard.any_instance.stub(:save).and_return(false)
        post :create, {:wizard => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wizard" do
        wizard = Wizard.create! valid_attributes
        # Assuming there are no other wizards in the database, this
        # specifies that the Wizard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wizard.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => wizard.to_param, :wizard => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested wizard as @wizard" do
        wizard = Wizard.create! valid_attributes
        put :update, {:id => wizard.to_param, :wizard => valid_attributes}, valid_session
        assigns(:wizard).should eq(wizard)
      end

      it "redirects to the wizard" do
        wizard = Wizard.create! valid_attributes
        put :update, {:id => wizard.to_param, :wizard => valid_attributes}, valid_session
        response.should redirect_to(wizard)
      end
    end

    describe "with invalid params" do
      it "assigns the wizard as @wizard" do
        wizard = Wizard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wizard.any_instance.stub(:save).and_return(false)
        put :update, {:id => wizard.to_param, :wizard => { "name" => "invalid value" }}, valid_session
        assigns(:wizard).should eq(wizard)
      end

      it "re-renders the 'edit' template" do
        wizard = Wizard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wizard.any_instance.stub(:save).and_return(false)
        put :update, {:id => wizard.to_param, :wizard => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wizard" do
      wizard = Wizard.create! valid_attributes
      expect {
        delete :destroy, {:id => wizard.to_param}, valid_session
      }.to change(Wizard, :count).by(-1)
    end

    it "redirects to the wizards list" do
      wizard = Wizard.create! valid_attributes
      delete :destroy, {:id => wizard.to_param}, valid_session
      response.should redirect_to(wizards_url)
    end
  end

end
